name: Build and Deploy  # 工作流名称

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # 在最新的Ubuntu操作系统上运行任务

    steps:
      - name: 检出代码库
        uses: actions/checkout@v4  # 使用GitHub官方的checkout action，用于检出代码库
        with:
          ref: main

      - name: 安装和配置Java环境  # 设置JDK
        uses: actions/setup-java@v4   # 使用GitHub官方的setup-java action，用于安装和配置Java环境
        with:
          java-version: 8
          distribution: "adopt"
          cache: maven

      - name: 使用Maven构建项目  # 使用Maven构建项目 ceshi
        run: mvn -am package -Dmaven.test.skip=true --batch-mode  # 执行mvn package命令进行项目构建

      - name: 列出文件  # 列出文件
        run: ls -R  # 执行ls -R命令，列出工作目录下的文件和子目录

      - name: 删除JAR文件  # 删除JAR文件
        uses: appleboy/ssh-action@v1.0.3  # 使用appleboy的ssh-action，用于在服务器上执行SSH命令
        with:
          host: ${{ secrets.SERVER_HOST }}  # 设置服务器主机
          username: ${{ secrets.SERVER_USERNAME }}  # 设置服务器用户名
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/app/target/
            rm -rf app.jar

      - name: 上传JAR文件到服务器  # 上传JAR文件到服务器
        uses: appleboy/scp-action@v0.1.7   # 使用appleboy的scp-action，用于将文件复制到远程服务器
        with:
          host: ${{ secrets.SERVER_HOST }}  # 设置服务器主机
          username: ${{ secrets.SERVER_USERNAME }}  # 设置服务器用户名
          password: ${{ secrets.PASSWORD }}
          source: ./target/app.jar  # 设置本地要上传的JAR文件路径
          target: /root/app/  # 设置远程服务器上的目标路径

      - name: 在服务器上执行shell脚本  # 在服务器上执行shell脚本
        uses: appleboy/ssh-action@v1.0.3  # 使用appleboy的ssh-action，用于在服务器上执行SSH命令
        with:
          host: ${{ secrets.SERVER_HOST }}  # 设置服务器主机
          username: ${{ secrets.SERVER_USERNAME }}  # 设置服务器用户名
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/app/target/
            ps -ef | grep app.jar | grep -v grep | awk '{print $2}' | xargs kill -9 
            nohup java -Dspring.profiles.active=test -jar app.jar > nohup.out &
            exit